### ISSUE TITLE
Plot - file to display get reset to default always

### ISSUE THREAD

**Issue by scrinzi** [GT-Nexus/AMOS-Gateway#17]
The chosen file type under "Data to plot" (e.g. Laser, spec_total etc.) is not saved, rather jumps back to its first entry "expec" when displaying a plot. 

Should keep previous choice, as e.g. in the "with parameters below". This was realized internally by putting the most recent coice on top of the display options.

**Comment by spamidig** [comment]
Can not reproduce this in both dev and production gateways. Perhaps we should sit and see together.

**Comment by scrinzi** [comment]
Hi, just checked. Now works as desired, indeed. Maybe with most recent pull? Works on both Chrome and Firefox.
